BlazorBattControl.NetDaemon.FoxBatteryControlSettings:
  ApiKey: ###########-YOUR-API-KEY-##########  
  DeviceSN: #YOUR-DEVICE-SERIAL-NUMBER#
  DisablePrice: 0.075
  ChargePrice: 0.075
  CurrentRateEntityID: sensor.octopus_energy_electricity_YOUR_ACC_&_METER_NUMBER_current_rate
  OffPeakFlagEntityID: binary_sensor.octopus_energy_electricity_YOUR_ACC_&_METER_NUMBER_off_peak
  DefaultSchedule:
      Groups:
      - WorkMode: ForceCharge
        Enabled: 1
        MinSocOnGrid: 20
        FdSoc: 20
        FdPwr: 0
        StartHour: 0
        StartMinute: 0
        EndHour: 5
        EndMinute: 29
      - WorkMode: Backup
        Enabled: 1
        MinSocOnGrid: 20
        FdSoc: 20
        FdPwr: 0
        StartHour: 23
        StartMinute: 30
        EndHour: 23
        EndMinute: 59

